# Generated by Django 6.0.4 on 2026-04-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_attachment_complaintrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reopen_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
